version: '3.7'

services:
  server:
    image: data-catcher-app-server
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-catcher-app-server
    environment:
      - NODE_ENV=production
    ports:
      - '80:4000'
    restart: always

